name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    env:
      HEADLESS: true

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Node.js dependencies
        run: npm install

      - name: Lint Code
        run: node src/js/launcher.js

      - name: Node Tests
        run: npm test

      - name: Archive Code Coverage Report
        continue-on-error: true
        uses: actions/upload-artifact@v2
        with:
          name: Code Coverage Report
          path: reports/
