name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    env:
      HEADLESS: true

    steps:
      - uses: actions/checkout@v4

      - name: Configure default git branch
        run: git config --global init.defaultBranch main

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Node.js dependencies
        run: npm install

      - name: Node Tests
        run: npm test

      - name: Archive Code Coverage Report
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: Code Coverage Report
          path: reports/

      - name: Lint Code
        run: npm run lint
