name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]

    env:
      HEADLESS: true

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Use NPM 6.x
        run: npm install -g npm@6

      - name: Install Node.js dependencies
        run: npm install

      - name: Lint Code
        run: npm run lint

      - name: Node Tests
        run: npm test

      - name: Archive Code Coverage Report
        continue-on-error: true
        uses: actions/upload-artifact@v2
        with:
          name: Code Coverage Report
          path: reports/
